import UserData from './UserData';
import UserId from './UserId';
import UserContact from './UserContacts';
import lastAppliedOption from './Options';
import InitialData from './InitialData';
import {combineReducers} from 'redux';

const rootReducer=combineReducers({
    datas:UserData,                  //Hold all datas from the API and it used for Authentication
    userdata:UserId,                 //Hold Login'ed user id that was generated by the API
    contact:UserContact,             //Hold all Current Contact Datas of the Login'ed user
    lastApplied:lastAppliedOption,   //Hold the lastApplied sort by the user
    initialData:InitialData          //Hold initial datas of user got from API
})

export default rootReducer